In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Create a null vector of size 10 but the fifth value which is 1.

a = np.nan * np.empty(10)
a[4] = 1
print("Output : \n",a)

In [ ]:
# Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of 
# the array.

a,b = map(int,input("Enter two number : ").split(' '))
c = np.random.random((a,b))
print("Array : ",c)
print("Mean : ",np.mean(c))

In [ ]:
# Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to 
# function.
# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]

def array2d(a,b):
    c = np.ones((a,b),dtype=np.int8)
    c[1:-1,1:-1] = 0
    return c

print("Output : \n",array2d(4,4))

In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.

a = np.linspace(0,1,12)[1:-1]
print("Output : \n",a)

In [ ]:
# Can you create a identity matrix of shape (3,4). If yes write code for it.
# No
np.identity(4),np.eye(3)

In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4.

a = np.random.random((5,5))*4
print("Output:\n",a)

In [ ]:
# Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point 
# as array is given. Create an array of distance of each point in the random vector from the given point. Distance array should
# be integer type.

a = np.random.randint(100,size = (10,2))
point = np.array([2,3])
distance = np.sqrt(np.sum((a-point)**2,axis=1)).astype(int)
print("Output : \n",distance)

In [ ]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

np.unravel_index(100, (6,7,8))

In [ ]:
# You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
# Input Format:
# A single line of input containing space separated numbers.
# Output Format:
# Print the reverse NumPy array with type float.
# Input:
# 1 2 3 4 -8 -10
# Output:
# [-10.  -8.   4.   3.   2.   1.]

a = input().split(" ")
print("Output : \n",np.array(a[::-1],dtype=float))

In [ ]:
# Elements count
# Count the number of elements of a numpy array.
# Input:
# np.array([])
# Output:
# elements_count :  0
# Input:
# np.array([1, 2])
# Output:
# elements_count :  2

a = np.array([])
print("No of element in an array : ",a.size)

In [ ]:
# Softmax function
# Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, 
# otherwise raise error.
# σ(z⃗ )i = ezi/∑Kj=iezj
# Input:
# [86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
# Output:
# [2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 5.05514197e-22, 1.50974911e-22]
# Input:
# [33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
# Output:
# [4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05, 1.39571531e-10, 9.99896577e-01]

def softmax(arr):
    if(arr.ndim==1 or type(arr)!=np.ndarray):
            result = np.exp(arr)/np.sum((np.exp(arr)))
            return result
    else:
        print("Pass only 1d array.")
        
arr = np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318])
print("Output : \n",softmax(arr))

In [ ]:
# Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new 
# array as result. The function only accepts the numpy array, otherwise raise error
# Input:
# a= [[0 1 2 3 4]
#  [5 6 7 8 9]]
# b= [[1 1 1 1 1]
#  [1 1 1 1 1]]
# Output:
# [[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]
# Input:
# a= [[0 1 2 3 4]
#  [5 6 7 8 9]]
# b= [[1 1 1 1 1]
#  [1 1 1 1 1]]
# c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
#  [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
# Output:
# [[0.         1.         2.         3.         4.        ]
#  [5.         6.         7.         8.         9.        ]
#  [1.         1.         1.         1.         1.        ]
#  [1.         1.         1.         1.         1.        ]
#  [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
#  [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]

def v_stack(*args):
    for i in args:
        if(type(i) != np.ndarray):
            raise TypeError("Pass only numpy array")
    else:
        return np.vstack(args)
        
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
# c = [1,2,3]
c = np.array([[0.10117373,0.1677244,0.73764059,0.83166097,0.48985695],[0.44581567,0.13502419,0.55692335,0.16479622,0.61193593]])
print("Output : \n",v_stack(a,b,c))

In [ ]:
# Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between 
# those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6.
# The end date should be included and for simplicity, choose dates from a same year.
# Input:
# date_array(start = '2020-09-15', end = '2020-09-25')
# Output:
# ['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
#  '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
#  '2020-09-23', '2020-09-24', '2020-09-25']
# Input:
# date_array(start = '2022-12-01', end = '2022-12-06')
# Output:
# ['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
# Input:
# date_array(start = '2020-11-25', end = '2020-11-30')
# Output:
# ['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
#  '2020-11-29', '2020-11-30']

def date_array(start,end):
    if(type(start)!=str or type(end)!=str):
        raise TypeError("Date is not in string format")
    total_days_of_month = {"01":31,"02":28,"03":31,"04":30,"05":31,"06":30,"07":31,"08":31,"09":30,"10":31,"11":30,"12":31}
    end = end.split("-")
    end_last = int(end[-1])+1
    if(total_days_of_month[end[-2]]<end_last):
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f"0{days_diff}" if days_diff<10 else f"{days_diff}"
        next_month = int(end[-2]) + 1
        end[-2] = f"0{next_month}" if next_month<10 else f"{next_month}"
    else:
        end[-1] = f"0{end_last}" if (end_last<10) else f"{end_last}"
    end = "-".join(end)
    return np.arange(start,end,dtype='datetime64[D]')
              
print("Output : \n",date_array(start='2022-11-15',end='2022-11-30'))

In [ ]:
# Subtract the mean of each row from a matrix.

arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
result = arr1 - np.mean(arr1,axis=1,keepdims=True)
print("Output : \n",result)

In [ ]:
# Swap column-1 of array with column-2 in the array.

a = np.random.random((3,3))
print("Original array : \n",a)
result = a[:,[0,2,1]]
print("Final array : \n",result)

In [ ]:
# Replace odd elements in arrays with -1.

a = np.random.randint(100,size=(10,2))
print("Original array : \n",a)
a[a%2==1] = -1
print("\nNew array : \n",a)

In [ ]:
# Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
# a=np.array([6,3,1,5,8])
# b=np.array([3,2,1,7,2])
# Result-> [6 3 1 7 8]

a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
a[b>a] = b[a<b]
print("Result : ",a)

In [ ]:
# Answer below asked questions on given array:
# 1. Fetch Every alternate column of the array
# 2. Normalise the given array
# There are different form of normalisation for this question use below formula.
# Xnormalized = (X−Xmin)/(Xmax−Xmin) 
# arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr2 = arr1[:,::2]
print("Output : \n",arr2)
Xmax = arr1.max()
Xmin = arr1.min()
Xnormalized = (arr1 - Xmin)/(Xmax-Xmin)
print("Normalized array : \n",Xnormalized)

In [ ]:
# Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}
# Output: The output should be the nth largest item out of the array
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

def nth_largest(arr,n):
        if(n<=len(arr)):
            return np.sort(arr)[-n]
        else:
            raise IndexError("n is out of the limit")

arr=np.array((12,34,40,7,1,0))
print("Output : ",nth_largest(arr,1))

In [ ]:
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])
np.hstack((np.repeat(a,3),np.tile(a,3)))

In [ ]:
# Find the nearest element in the array to a given integer.
# a=23 and array - [10 17 24 31 38 45 52 59].
# Nearest element is 24
# Hint: Read about this function argmin()

arr =  np.array([10,17,24,31,38,45,52,59])
a = 23
print("Nearest element is : ",arr[np.argmin(abs(arr-a))])

In [ ]:
# Replace multiples of 3 or 5 as 0 in the given array.
# arr=[1 2 3 4 5 6 7 9]
# result-> [1 2 0 4 0 0 7 0]

arr = np.array([1,2,3,4,5,6,7,9])
arr[(arr%3==0) | (arr%5==0)]=0
print("Output : ",arr)

In [ ]:
# Use Fancy Indexing.
# Double the array elements at given indexes
# arr = np.arange(10)
# indexes = [0,3,4,9]
# Result -> [ 0 1 2 6 8 5 6 7 8 18]
# Using a given array make a different array as in below example
# array = [1,2,3]
# result array -> [1 1 1 2 2 2 3 3 3]
# Internal-repetion should be as length of the array.
# Hint:
# if a is an array
# a = [2,4]
# a[[1,1,0,1]] will result in-> [4 4 2 4]

arr = np.arange(10)
indexes = [0,3,4,9]
arr[indexes] *=2
print("Output\n",arr)

arr = np.array([1,2,3])
indexes = []
for index in range(len(arr)):
    indexes.extend([index]*len(arr))
print("Output\n",arr[indexes])

In [ ]:
# Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the 
# array.
# arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
d = {}
value = 0
for i in arr.flatten():
    if(~np.isnan(i)):
        d.setdefault(i, 0)
        d[i] +=1
arr[np.isnan(arr)] = sorted(d.items(),key=lambda x:x[1])[-1][0]
print("Output\n",arr)

In [ ]:
# Write a NumPy program
# to find the missing data in a given array. Return a boolean matrix.also try to fill those missing values with 0. For that, 
# you can use np.nan_to_num(a)
# import numpy as np
# np.array([[3, 2, np.nan, 1],
#           [10, 12, 10, 9],
#           [5, np.nan, 1, np.nan]])

arr = np.array([[3, 2, np.nan, 1],[10, 12, 10, 9],[5, np.nan, 1, np.nan]])
print("Output\n",np.nan_to_num(arr,0))

In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C.
# Cij =1/(xi - yj)
# x = numpy.array([1,2,3,4]).reshape((-1, 1))
# y = numpy.array([5,6,7])

x = np.array([1,2,3,4]).reshape((-1, 1))
y = np.array([5,6,7])
def cauchy_matrix(x,y):
    c = 1/(x-y)
    return c

print("Cauchy Matrix\n",cauchy_matrix(x,y))

In [ ]:
# Plot this below equation.
# y = (e^x−e^−x)/(e^x+e^−x)
# Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some 
# difference between the sigmoid function and this tanh function, note that to your notebook

x = np.linspace(-10,10,100)
y = (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
plt.plot(x,y)

In [ ]:
# Plot the below equation.
# y = (36−(x−4)^2)**0.5+2
# The range of x should be between -2 to 10.  x∈[−2,10]

x = np.linspace(-2,10,100)
y = (36-(x-4)**2)**0.5 + 2
plt.plot(x,y)

In [ ]:
# Write a program implement Boradcasting Rule to check if two array can be added or not.
# Given tuples of shapes.
# shape of a- (3,2,2)
# shape of b- (2,2)
# check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)

def check_broadcast(a,b):
    a = a[::-1]
    b = b[::-1]
    for ai,bi in zip(a,b):
        if(ai !=bi and ai !=1 and bi !=1):
            return "Not Broadcasted"
    return "Broadcasted"
print("Output : ",check_broadcast((4,3,1,5),(2,5)))

In [ ]:
# Create a random 3x4 matrix with value between 0-100. And perform below tasks
# i. Sort this matrix. np.sort()
# ii. Sort this matrix based on values in 2nd column.
# iii. Sort this matrix based on max value in each row.
# iv. Sort based on elements value.
# arr = 
#     [[92 90 74]
#     [ 6 63 93]
#     [15 93 96]
#     [70 60 48]]
# i. np.sort
# [[74 90 92]
#  [ 6 63 93]
#  [15 93 96]
#  [48 60 70]]
# ii. based on 2nd column
# [[70 60 48]
#  [ 6 63 93]
#  [92 90 74]
#  [15 93 96]]
# iii. based on row max- ascending
# [[15 93 96]
#  [ 6 63 93]
#  [92 90 74]
#  [70 60 48]]
# iv. based on elements value
# [[ 6 15 48]
#  [60 63 70]
#  [74 90 92]
#  [93 93 96]]

arr = np.array([92,90,74,6,63,93,15,93,96,70,60,48]).reshape(4,3)                                             
print("Sorted array\n",np.sort(arr))
print("Sorted array based on 2nd column\n",arr[np.argsort(arr[:,1])])
print("Sorted array based on row max- ascending\n",np.array(sorted(arr,key=lambda x:max(x))))
print("Sorted array based on elements value\n",np.sort(arr.flatten()).reshape(4,3))

In [ ]:
# There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
# i. Add marks every student of an extra subject in the same array.
# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
# iii. Add extra column with sum of all subjects(5-subjects) marks
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
# Note: Change dimension of arrays during concatenation or appending if required.
# Given Array-
# marks = [[13, 10,  9, 33],
#        [63, 46, 90, 42],
#        [39, 76, 13, 29],
#        [82,  9, 29, 78],
#        [67, 61, 59, 36]]
# extra_subject = [41, 87, 72, 36, 92]
# # Two extra students record-
# rec1 = [77, 83, 98, 95, 89]
# rec2 = [92, 71, 52, 61, 53]

marks = np.array([[13, 10,  9, 33],[63, 46, 90, 42],[39, 76, 13, 29],[82,  9, 29, 78],[67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1,1)
marks = np.concatenate([marks,extra_subject], axis=1)
print("Marks\n",marks)
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
marks = np.append(marks,(rec1,rec2),axis=0)
print("Marks\n",marks)
marks = np.concatenate([marks,np.sum(marks,axis=1,keepdims=True)], axis=1)
print("Marks\n",marks)
print("Marks\n",np.array(sorted(marks,key=lambda x:x[-1],reverse=True))[:2,])

In [ ]:
# Find unique arrays from a 2D array column wise and row wise.
# arr = np.array([[1,2,3,3,1,1],
#                 [0,9,1,2,8,8],
#                 [1,2,3,8,8,8],
#                 [1,2,3,3,1,1]])
# Expected Result-
# Row Wise
# [[0 9 1 2 8 8]
#  [1 2 3 3 1 1]
#  [1 2 3 8 8 8]]
# Col Wise
# [[1 1 2 3 3]
#  [0 8 9 1 2]
#  [1 8 2 3 8]
#  [1 1 2 3 3]]

arr = np.array([[1,2,3,3,1,1],[0,9,1,2,8,8],[1,2,3,8,8,8],[1,2,3,3,1,1]])
print("Row Wise\n",np.unique(arr,axis=0))
print("Column Wise\n",np.unique(arr,axis=1))

In [ ]:
# Flip given 2-D array along both axes at the same time.

arr = [[13, 10,  9, 33],[63, 46, 90, 42],[39, 76, 13, 29],[82,  9, 29, 78],[67, 61, 59, 36]]
print("Output\n",np.flip(arr))

In [ ]:
# Get row numbers of NumPy array having element larger than X.
# arr = [[1,2,3,4,5], 
#       [10,-3,30,4,5], 
#       [3,2,5,-4,5], 
#       [9,7,3,6,5]] 
# X = 6

arr = np.array([[1,2,3,4,5],[10,-3,30,4,5],[3,2,5,-4,5],[9,7,3,6,5]])
x = 6
print("Output : ",np.where(np.any(arr>x,axis=1))[0])

In [ ]:
# How to convert an array of arrays into a flat 1d array?
# These arrays are given.
# arr1 = np.arange(3)
# arr2 = np.arange(3,7)
# arr3 = np.arange(7,10)

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10) 
print("Output\n",np.concatenate([arr1,arr2,arr3]))

In [ ]:
# You are given a array. You have to find the minimum and maximum array element and remove that from the array.
# import numpy as np
# np.random.seed(400)
# arr = np.random.randint(100, 1000, 200).reshape((1, 200))

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print("Output\n",np.delete(arr,[np.argmax(arr),np.argmin(arr)]))

In [ ]:
# You are given an arrays. You have to limit this array's elements between 100 to 200.  arr∈[100,200] . So replace those values 
# accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

arr = np.random.randint(0, 2000, 500)
print("Output\n",np.cumsum(np.sort(np.clip(arr,a_min=100,a_max=200))))

In [ ]:
# You are given a array ( arr∈[0,1] ). First you have round off the elements upto 3 decimal places and compare that
# 0th percentile == minimum value of the array
# 100th percentile == maximum value of the array
# also find the difference betwen 51th percenile and 50th percentile values

arr = np.around(np.linspace(0,1,100),3)
print("0th percentile == minimum value of the array : ",np.percentile(arr,0)==np.min(arr))
print("100th percentile == maximum value of the array : ",np.percentile(arr,100)==np.max(arr))
print("Difference between 51st percentile and 50st percentile value : ",round(np.percentile(arr,51)-np.percentile(arr,50),3))